In [1]:
import pandas
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
import warnings
warnings.filterwarnings('ignore')

In [7]:
dataset = pandas.read_csv('heart.csv')

In [8]:
print(dataset.head(20))

    age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0    63    1   3       145   233    1        0      150      0      2.3   
1    37    1   2       130   250    0        1      187      0      3.5   
2    41    0   1       130   204    0        0      172      0      1.4   
3    56    1   1       120   236    0        1      178      0      0.8   
4    57    0   0       120   354    0        1      163      1      0.6   
5    57    1   0       140   192    0        1      148      0      0.4   
6    56    0   1       140   294    0        0      153      0      1.3   
7    44    1   1       120   263    0        1      173      0      0.0   
8    52    1   2       172   199    1        1      162      0      0.5   
9    57    1   2       150   168    0        1      174      0      1.6   
10   54    1   0       140   239    0        1      160      0      1.2   
11   48    0   2       130   275    0        1      139      0      0.2   
12   49    1   1       13

In [4]:
#not required
#names = ['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','target']

#Initial Accuracy

In [129]:
#u
X = dataset.drop('target',axis = 1)
Y = dataset['target']

In [225]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.20)

In [226]:
classifier = DecisionTreeClassifier()
classifier.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [227]:
y_pred = classifier.predict(X_test)

In [228]:
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[14 11]
 [10 26]]
              precision    recall  f1-score   support

         0.0       0.58      0.56      0.57        25
         1.0       0.70      0.72      0.71        36

    accuracy                           0.66        61
   macro avg       0.64      0.64      0.64        61
weighted avg       0.65      0.66      0.65        61



got an accuracy of 67% need to improve the algorithm

# Univariant Feature selection

In [134]:
from sklearn.feature_selection import SelectKBest

In [135]:
array = dataset.values


In [142]:
print(dataset.shape)

(303, 14)


In [143]:

X = array[:,0:13]

Y = array[:,13]

In [144]:
from sklearn.feature_selection import chi2
test = SelectKBest(score_func=chi2, k=4)

In [145]:
fit = test.fit(X, Y)

In [146]:
features = fit.transform(X)

In [147]:
print(features)

[[  3.  150.    2.3   0. ]
 [  2.  187.    3.5   0. ]
 [  1.  172.    1.4   0. ]
 ...
 [  0.  141.    3.4   2. ]
 [  0.  115.    1.2   1. ]
 [  1.  174.    0.    1. ]]


In [148]:
import numpy
numpy.set_printoptions(precision=3)

In [149]:
print(fit.scores_)

[ 23.287   7.577  62.598  14.824  23.936   0.203   2.978 188.32   38.914
  72.644   9.804  66.441   5.792]


In [150]:
print(features[0:5,:])

[[  3.  150.    2.3   0. ]
 [  2.  187.    3.5   0. ]
 [  1.  172.    1.4   0. ]
 [  1.  178.    0.8   0. ]
 [  0.  163.    0.6   0. ]]


In [151]:
print(len(fit.scores_))

13


In [152]:
dataset1 = dataset[['thalach','ca','oldpeak','cp','exang','age','target']]

In [153]:
print(dataset1)

     thalach  ca  oldpeak  cp  exang  age  target
0        150   0      2.3   3      0   63       1
1        187   0      3.5   2      0   37       1
2        172   0      1.4   1      0   41       1
3        178   0      0.8   1      0   56       1
4        163   0      0.6   0      1   57       1
..       ...  ..      ...  ..    ...  ...     ...
298      123   0      0.2   0      1   57       0
299      132   0      1.2   3      0   45       0
300      141   2      3.4   0      0   68       0
301      115   1      1.2   0      1   57       0
302      174   1      0.0   1      0   57       0

[303 rows x 7 columns]


In [229]:
X1 = dataset1.drop('target',axis = 1)
Y1 = dataset1['target']

In [230]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1,Y1,test_size = 0.20)

In [231]:
classifier = DecisionTreeClassifier()
classifier.fit(X1_train,Y1_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [232]:
y1_pred = classifier.predict(X1_test)

In [233]:
print(confusion_matrix(Y1_test,y1_pred))
print(classification_report(Y1_test,y1_pred))

[[20  5]
 [ 8 28]]
              precision    recall  f1-score   support

           0       0.71      0.80      0.75        25
           1       0.85      0.78      0.81        36

    accuracy                           0.79        61
   macro avg       0.78      0.79      0.78        61
weighted avg       0.79      0.79      0.79        61



# After feature selection the accuracy increased to 79%

# Recursive Feature Elimination

In [159]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [160]:
model = LogisticRegression() 
rfe = RFE(model, 3)

In [161]:
fit = rfe.fit(X, Y)

/home/arun/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/arun/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/arun/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/arun/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/arun/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22.

In [162]:
print("Num Features: %d"% fit.n_features_) 
print("Selected Features: %s"% fit.support_) 
print("Feature Ranking: %s"% fit.ranking_)

Num Features: 3
Selected Features: [False  True False False False False False False  True False  True False
 False]
Feature Ranking: [10  1  3  8 11  9  6  7  1  5  1  2  4]


In [282]:
from sklearn.utils import shuffle
dataset2 = shuffle(dataset[['thalach','ca','oldpeak','cp','exang','slope','target']])

In [283]:
dataset2.head(10)

thalach  ca  oldpeak  cp  exang  slope  target
129      121   1      0.2   1      1      2       1
4        163   0      0.6   0      1      2       1
172      160   0      1.8   1      0      1       0
290      161   1      0.0   0      0      2       0
293      150   0      0.8   2      0      1       0
300      141   2      3.4   0      0      1       0
65       182   0      1.4   0      0      2       1
302      174   1      0.0   1      0      1       0
159      163   0      0.0   1      0      2       1
179      112   1      0.6   0      1      1       0

In [284]:
print(dataset2)

     thalach  ca  oldpeak  cp  exang  slope  target
129      121   1      0.2   1      1      2       1
4        163   0      0.6   0      1      2       1
172      160   0      1.8   1      0      1       0
290      161   1      0.0   0      0      2       0
293      150   0      0.8   2      0      1       0
..       ...  ..      ...  ..    ...    ...     ...
43       143   0      0.4   0      0      1       1
181      114   3      1.0   0      0      1       0
164      173   4      0.0   2      0      2       1
67       175   0      0.6   1      0      1       1
121      182   0      0.0   0      0      2       1

[303 rows x 7 columns]


In [285]:
X2 = dataset2.drop('target',axis = 1)
Y2 = dataset2['target']
print(X2)

     thalach  ca  oldpeak  cp  exang  slope
129      121   1      0.2   1      1      2
4        163   0      0.6   0      1      2
172      160   0      1.8   1      0      1
290      161   1      0.0   0      0      2
293      150   0      0.8   2      0      1
..       ...  ..      ...  ..    ...    ...
43       143   0      0.4   0      0      1
181      114   3      1.0   0      0      1
164      173   4      0.0   2      0      2
67       175   0      0.6   1      0      1
121      182   0      0.0   0      0      2

[303 rows x 6 columns]


In [286]:
from sklearn.model_selection import train_test_split
X2_train, X2_test, Y2_train, Y2_test = train_test_split(X2,Y2,test_size = 0.20)

In [287]:
classifier = DecisionTreeClassifier()
classifier.fit(X2_train,Y2_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [288]:
y2_pred = classifier.predict(X2_test)

In [289]:
print(confusion_matrix(Y2_test,y2_pred))
print(classification_report(Y2_test,y2_pred))

[[13  6]
 [ 9 33]]
              precision    recall  f1-score   support

           0       0.59      0.68      0.63        19
           1       0.85      0.79      0.81        42

    accuracy                           0.75        61
   macro avg       0.72      0.73      0.72        61
weighted avg       0.77      0.75      0.76        61



 if <thalach> <= 0.5:
  if <ca> <= 0.5:
   if <oldpeak> <= 0.7:
    if <cp> <= 41.5:
     return[[3. 0.]]
    else:
     if <age> <= 1.5:
      if <sex> <= 47.0:
       return[[0. 3.]]
      else:
       if <target> <= 0.5:


IndexError: list index out of range